STAGING_INCLUDE := $(STAGING_DIR)/include
STAGING_LIB := $(STAGING_DIR)/lib

CCFLAGS := -I$(STAGING_INCLUDE)
CFLAGS := $(CCFLAGS) -std=c99
CXXFLAGS := $(CCFLAGS) -std=c++11
LDFLAGS := -L$(STAGING_LIB)
